window:
  type: "toolbar" # Valid window types: dock, toolbar
  dock: "top" # Dock the window to the top or bottom of the screen

  size:
    height: 18 # Accepted values are integers or percentages
    width: "100%" # Accepted values are integers, percentages or 'auto'

  padding:
    # Accepted values are integers or percentages
    left: 0
    right: 0
    top: 0

