window:
  # dock, toolbar
  type: "toolbar"

  # Dock the window to the top or bottom of the screen
  dock: "top"
  size:
    # Accepted values are integers or percentages
    height: 24

    # Accepted values are integers, percentages or 'auto'
    width: "auto"

  padding:
    # Accepted values are integers or percentages
    left: 18
    right: 18
    top: 8

    # Only used when docked bottom
    botom: 0


elements:
  time:
    refresh: 1000
    format: "%l:%M"

  date:
    refresh: 300000
    format: "%a %b %d"

  battery:
    refresh: 30000
    # last_charge | total
    capacity: "last_charge"

  i3-workspaces:
    # Style
    #   name: shows the name of each workspace
    #   bullet: shows a bullet for each workspace
    style: "bullet"

  volume:
    refresh: 1000

